version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: ${MONGO_URI}
      URL_SUNAT: ${URL_SUNAT}
      JWT_SECRET: ${JWT_SECRET}



