version: '3.8'

services:
  backend:
    container_name: nestjs
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
