name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      URL_SUNAT: ${{ secrets.URL_SUNAT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t laboratoria013/backend-kambista:latest .
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker push laboratoria013/backend-kambista:latest

      - name: SSH into EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}  
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            echo "SSH connection established."
            docker pull laboratoria013/backend-kambista:latest
            docker stop kambista || true  # Detener el contenedor existente, si existe
            docker rm kambista || true    # Eliminar el contenedor existente, si existe
            docker run -d -p 80:3000 --name kambista \
              -e PORT=${{ secrets.PORT }} \
              -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
              -e URL_SUNAT=${{ secrets.URL_SUNAT }} \
              laboratoria013/backend-kambista:latest
